include/termcolor/termcolor.hpp

Former code fired segmentation fault if output stream was `std::clog`. `stdio` doesn't know about log stream, we assume it's an error stream instead.

Add support for clog stream

---

include/termcolor/termcolor.hpp

`OS_*` macros might clash, rename to `TERMCOLOR_OS_*`
Signed-off-by: nabijaczleweli \<nabijaczleweli@gmail.com\>

Try not to clash with macro names

---

include/termcolor/termcolor.hpp

As defined in 2.10.3 (http://eel.is/c++draft/lex.name#3):
In addition, some identifiers are reserved for use by C++ implementations and shall not be used otherwise [...].
— Each identifier that contains a double underscore __ [...] is reserved to the implementation for any use.
Signed-off-by: nabijaczleweli \<nabijaczleweli@gmail.com\>

Don't use a reserved identifier for the internal namespace

---

include/termcolor/termcolor.hpp

getting linking errors about multiple definitions on windows platform, making functions inline should fix this

making windows functions inline

---

docs/index.rst
include/termcolor/termcolor.hpp
test/test.cpp

So far termcolor aimed to colorize only those streams that are bound to
TTY (terminal). However, it's not always the case and sometimes we need
to colorize (i.e. write ANSI escape sequences) text even in plain
stringstreams, so when we print them to TTY - it will be colorized.
For this case two new manipulators were added:
* colorize
* nocolorize
which are enable and disable colorization respectively.
Usage:
std::stringstream ss;
ss << termcolor::colorize << termcolor::blue << "Hej!";
Fixes #5

Colorize std::stringstream if 'colorize' is passed

---

CMakeLists.txt
cmake/config.cmake.in

- Add interface library for termcolor and add it to install target
- Add ability to toggle creation of tests
- Add test target
- Generate termcolor-config.cmake and install it
- Make it possible to use termcolor with find_package in other projects
- Add alias termcolor::termcolor to match the installed target name
- Make it possible to add termcolor as subproject in other projects
- Require CMake 3.0 for INTERFACE library
These changes would make it trivial to add this Package to [Hunter](https://github.com/ruslo/hunter/issues/1482)

add install step and config generation

---

.travis.yml
CMakeLists.txt
cmake/config.cmake.in
examples/cmake-external/CMakeLists.txt
examples/cmake-external/example.cpp
examples/cmake-package/CMakeLists.txt
examples/cmake-package/example.cpp
examples/cmake-submodule/CMakeLists.txt
examples/cmake-submodule/example.cpp

CMake is a popular tool among C++ developers, however, not trivial and
covered with poor documentation. That's why it would be nice to provide
a couple of good examples of how one can use termcolor library by
utilizing CMake features. Besides, these examples could be used on CI to
ensure usecases are not broken.

Add CMake usage examples

---

.travis.yml
examples/cmake-fetch/CMakeLists.txt
examples/cmake-fetch/example.cpp

FetchContent module populating content at configure time via any method
supported by the ExternalProject module. Whereas ExternalProject_Add()
downloads at build time, the FetchContent module makes content available
immediately, allowing the configure step to use the content in commands
like add_subdirectory(), include() or file() operations.
In other words this is a modern way to use external libraries in your
projects.

Add CMake example using FetchContent module

---

.travis.yml
CMakeLists.txt

To make it simpler and easier to understand.
* No unnecessary comments.
* Calls are grouped by their purpose.
* `make run` target is removed because its name is too general and
termcolor can be used as a CMake submodule.

Reformat CMakeLists.txt

---

examples/cmake-fetch/CMakeLists.txt
examples/cmake-submodule/CMakeLists.txt

If EXCLUDE_FROM_ALL is not passed, termcolor's installation targets may
be propagated to main project. It's not what we are expecting.

Add EXCLUDE_FROM_ALL to some examples

---

test/test.cpp

Add test statements to test.cpp in order to visually ensure that both
std::clog and std::cerr streams can be formatted to if they are attached
to tty.

Ensure std::{clog,cerr} streams can be formatted

---

.travis.yml
CMakeLists.txt

It's time to embrace the standard that is almost 10 yo. However, it's
weird that even modern compilers provide its features as an extensions
yet the code is not built according to C++11 standard. :-/

Add 'std=c++11' compilation flag

---

include/termcolor/termcolor.hpp

color<>/on_color<> are new stream manipulators that can be used to use
any color from 256 color table. This table is not supported on Windows
but we don't want to trigger compilation errors in this case. Instead,
we want to be consistent with other manipulators which are not available
on windows and simply fallback to no-op.

Don't error when color/on_color is used on Windows

---

examples/cmake-external/CMakeLists.txt

All other examples are implicitly fetched C++11 requirements from
termcolor's cmake definition. This example, however, completely ignores
it and hence it's required to explicitly set one.

Require C++11 for examples/cmake-external

---

include/termcolor/termcolor.hpp
test/test.cpp

I know there were still some discussions on whether to expose some sort of enum or type for a `color()` function, or an `intense()` function.
This is just to get the ball rolling on the specifics for each color, and the series of functions that I figure will get the most heavy public use.
Relates to https://github.com/ikalnytskyi/termcolor/issues/36

add high foreground/background colors, add tests for high colors

---

include/termcolor/termcolor.hpp

Termcolor is used to provide `colorize`/`nocolorize` stream manipulators
to colorize streams other than ones ties to TTY. Such streams are marked
by termcolor as capable to carry ASCII color codes. However, due to the
fact that the static variables are initialized per translation units, it
turns out that colorized stream returned by one translation unit to
another are not recognized as color capable. This patch makes things
right and ensures that the flag we use to store the marker is shared and
the same between translation units.
Fixes #54

Share colorization flag between translation units

---

include/termcolor/termcolor.hpp

In order to address a bunch of edge cases this patch introduces a set of
new macros to control Termcolor's behaviour in certain situations. See
changes summary below.
* Termcolor used to abort compilation if unsupported target platform is
detected. This patch changes this behaviour since colorization is not
assumed to be essential and hence it's better to noop rather than
abort compilation.
* Termcolor used to always use Windows API when target OS is Windows.
Now one can define TERMCOLOR_USE_ANSI_ESCAPE_SEQUENCES in order to
enforce ANSI escape sequences even for Windows. This is useful when
one wants to use ANSI escape sequences on Windows 10.
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
* Termcolor used to always colorize output if the platform is …

Add macros based API

---

CMakeLists.txt

Distributions like Fedora use /usr/lib64 for their 64bit versions and termcolor has hardcoded /usr/lib install path. By using `GNUInstallDirs` automatically can be detected which path should be used. Also apply to includedir to avoid hardcoded values.

Use GNUInstallDirs for install targets

---

CMakeLists.txt
include/termcolor/termcolor.hpp
test/subtest.cpp
test/subtest.hpp
test/test.cpp

The `inline` attribute has initially been used as a workaround to allow
function definitions in the header file. Templates are defined in
headers by design which means there's no need for `inline` attribute
anymore.

Strip inline attribute from templates

---

include/termcolor/termcolor.hpp

GCC13 reduced the amount of implicitly included headers (see https://gcc.gnu.org/gcc-13/porting_to.html). To compile termcolor with GCC13, cstdint now needs to be explicity included.
Explicitly including a header that was included implicitly before should normally not change the behaviour on other platforms or when building with a different compiler, but I can't check them all.

GCC13 compatibility: Explicitly include cstdint

---

cmake/config.cmake.in

If another project vendors termcolor (via `add_subdirectory`) and tries to install, the resulting package is not usable. 
Let's say the top level project has a CMakeLists.txt like this:
```
cmake_minimum_required(VERSION 3.20)
project(my_project)
add_subdirectory(termcolor)
```
The generated `termcolor-config.cmake` will want to include `my_project-targets.cmake` instead of `termcolor-targets.cmake`.
By changing `CMAKE_PROJECT_NAME` to `PROJECT_NAME` in `config.cmake.in` this problem is solved.

CMake: Allow install if non-toplevel project.
